"""serial table

Revision ID: 76cfb6d2063f
Revises: 
Create Date: 2024-09-18 16:24:02.236685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cfb6d2063f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CurrentSerial', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serial_number')
    # ### end Alembic commands ###
